# generic args
output_directory: output
random_seed: 0
problem_type: binary

# featurization
input_file: ../hiv_clean.csv
target_columns: target
smiles_column: smiles
descriptor_set: all

# training
number_repeats: 5
train_size: 0.7
val_size: 0.1
test_size: 0.2
sampler: random
