# generic args
output_directory: output
random_seed: 0
problem_type: regression

# featurization
input_file: ../qm8_12target.csv
target_columns: target_0 target_1 target_2 target_3 target_4 target_5 target_6 target_7 target_8 target_9 target_10 target_11
smiles_column: smiles
descriptor_set: all

# training
number_repeats: 5
train_size: 0.7
val_size: 0.1
test_size: 0.2
sampler: random
